# Generated by EventGenerator on 2021-06-15 01:09:27

"""
MIT License

Copyright (c) 2021 nanato12

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
from typing import Optional
from akad.ttypes import Message, MIDType, Operation
from line import LINE


def RECEIVE_MESSAGE(bot: LINE, op: Operation) ->None:
    """Operation No: 26

    Args:
        bot (LINE): LINE Client
        op (Operation): Operation
    """
    message: Optional[Message] = op.message
    if message is not None:
        if message.toType == MIDType.ROOM:
            to: str = message.to
        elif message.toType == MIDType.GROUP:
            to: str = message.to
        elif message.toType == MIDType.USER:
            to: str = message._from
        else:
            return
